- database/sql/schema.sql
Database scheme needs a change after discussion with frontend and reviewing algo data model docs. 
Fixes # (#28 )
> Update database schema

- docs/openapi/bundled.yaml
- docs/openapi/components/schemas/ArrayProfessors.yaml
- docs/openapi/components/schemas/Professor.yaml
- docs/openapi/components/schemas/ProfessorNoID.yaml
Just added an example for an array of professors.
> Added example for array of professors

- docs/openapi/bundled.yaml
- docs/openapi/components/schemas/Algorithm/AlgProfessor.yaml
- docs/openapi/components/schemas/AvailabilityDict.yaml
- docs/openapi/components/schemas/PreferredTime.yaml
- docs/openapi/components/schemas/PreferredTimes.yaml
- docs/openapi/components/schemas/ProfessorPreference.yaml
- docs/openapi/components/schemas/ProfessorPreferenceNoID.yaml
Replace preferred time examples with reference to schemas.
Fixes (#11 )
> Add preferred time property schema

- database/sql/schema.sql
Increased course_name to have 100 characters. 
Fixes # (issue)
> increased course_name to have 100 characters

- api/dbconn.py
This fixes an issue I was running into while debugging some stuff for frontend. This was not the root cause of the issue but kept on annoying me. Essentially when the API loses connection to the DB it is put in a un-recoverable fail state and needs to be restarted. This fixes that by checking that the API is connected to the DB before making a query.
Fixes #79
> check if db connection is alive

- api/app.py
- api/login.py
- database/init_data/admin.txt
- database/sql/z_init.sql
- demos/sprint3/demo.sh
- docs/openapi/bundled.yaml
- docs/openapi/components/schemas/LoginInput.yaml
- docs/openapi/components/schemas/LoginResponse.yaml
- docs/openapi/openapi.yaml
- docs/openapi/paths/login/login.yaml
This PR implements the login endpoint on a spec I agreed with frontend about. An example of ways to use this endpoint is also provided in the demos folder. This PR also adds a demo admin to the seed data so frontend will have someone to play with without needing to curl our endpoints.
Fixes #48
> Implement Login Endpoint

- api/preference.py
- database/sql/schema.sql
- docs/openapi/bundled.yaml
- docs/openapi/components/schemas/ProfessorPreference.yaml
- docs/openapi/components/schemas/ProfessorPreferenceNoID.yaml
Add semester off attribute to Professor Availability table 
Fixes # (#66 )
> Add semester off attribute to ProfessorAvailability

- api/app.py
This fixes an issue frontend was experiencing where they were being blocked
from using a PUT endpoint.
Fixes #91
> Allows POST, PUT, GET, and DELETE explicitly.

- database/init_data/algo_data/chem_101.json
- database/init_data/algo_data/econ_180.json
- database/init_data/algo_data/engr_110.json
- database/init_data/algo_data/engr_120.json
- database/init_data/algo_data/engr_130.json
- database/init_data/algo_data/engr_141.json
- database/init_data/algo_data/math_100.json
- database/init_data/algo_data/math_101.json
- database/init_data/algo_data/math_109.json
- database/init_data/algo_data/math_110.json
- database/init_data/algo_data/math_122.json
- database/init_data/algo_data/phys_110.json
- database/init_data/algo_data/phys_111.json
- database/init_data/algo_data/stat_260.json
Added Algo required static course data to repo.
Fixes #83
> Static course data import

- requirements.txt
Updates C1Algo1
Fixes # (issue)
> updated c1algo1

- api/course.py
- api/dbconn.py
Fix SQL query semantic error for GET courses to resolve issue with spring_req returning false for all courses. Also used bool instead of not in dbconn for bool converter. 
Fixes # (#114)
> Fix spring_req attribute returning false for all courses

- api/helper.py
- api/schedule.py
- requirements.txt
Added PUT /schedules, still need to add validator( I will do this in a separate PR)
Fixes #put
> added PUT /schedules endpoint, still need to add validator

- api/schedule.py
- requirements.txt
Updated both C1 algos and removed bug fix code that fixed an algo2 bug. 
> updated both algo packages and removed bug fix code

- api/populate_prof_prefs/prof_pref_inputter.py
- api/preference.py
Fix the issue with post pref endpoint giving 500 error for curl requests. This fix makes it compatible with curl requests and the prof pref inputter script. 
Fixes # (#122 )
> Fix post pref endpoint giving 500 error

- docs/openapi/bundled.yaml
- docs/openapi/paths/schedules/schedules_{id}.yaml
> updated POST /schedules docs

- api/course.py
- docs/openapi/bundled.yaml
- docs/openapi/components/schemas/Course.yaml
- docs/openapi/components/schemas/CourseNoID.yaml
Updated queries for courses endpoint to include `notes` attribute.
Fixes #132 
> 132 update post courses

- docs/openapi/bundled.yaml
- docs/openapi/paths/schedules/schedules.yaml
Removed POST /schedules
Fixes # (issue)
> removed post /schedules documentation

- requirements.txt
> updated alg1

- README.md
- tests/performance/Admin Scen.jmx
- tests/performance/Prof. Scen.jmx
Added performance test files to analyze the performance levels of our code.
Fixes #127 
>  Performance Test plan files and README update

- api/populate_prof_prefs/prof_pref_inputter.py
This PR adds a validation check to make sure that every course has at least one professor who would like to test it. It took a few goes to actually hit this edge case but when I did I verified that it actually did fix the situation.
Fixes #128
> Added way to check if a course is covered by a professor or not.

- api/init_data/fall_static_courses.json
- api/init_data/spring_static_courses.json
- api/init_data/summer_static_courses.json
- requirements.txt
Fixes a bug where we were unable to use company 2s algorithms.
Fixes #141
> IDs are now strings.

- api/helper.py
- api/init_data/fall_static_courses_c2.json
- api/init_data/spring_static_courses_c2.json
- api/init_data/summer_static_courses_c2.json
- api/schedule.py
- requirements.txt
Modifies input for C2 Algorithms. Updates C1 Algo1. 
> added fix to C2 algo input schedules

- api/populate_prof_prefs/prof_pref_inputter.py
- requirements.txt
Updates Alg1, changes prof pref inputter so profs select more courses
Fixes # (issue)
> updated alg1 and change prof pref inputter so profs select more courses:

- api/schedule.py
- requirements.txt
Update algo2 to version 1.0.1
Fixes # (#151 )
> Update c1algo2 version to 1.0.1

- docs/openapi/bundled.yaml
- docs/openapi/components/schemas/ArrayProfessorPreference.yaml
- docs/openapi/components/schemas/ProfessorPreference.yaml
- docs/openapi/paths/professors/professors_preferences_{id}.yaml
- docs/openapi/paths/professors/professors_{id}_preferences.yaml
Update docs for pref endpoints. 
Fixes # (#153 )
> Update docs for pref endpoints
